### ISSUE TITLE
IEEE has disappeared: add CRC_32_IEEE as a synonym for CRC_32_ISO_HDLC

### ISSUE THREAD

**Issue by BartMassey** [akhilles/crc-catalog#3]
The CRC known around the Internet as the "IEEE" CRC is used in a lot of things, for example PNG. In `crc` 1.4, it was simply known as `IEEE`. It turns out to be identical to `crc-catalog`'s `CRC_32_ISO_HDLC`, but that name seems kind of misleading since HDLC is not really a thing anymore.

It would be great to add `CRC_32_IEEE` as a synonym for `CRC_32_ISO_HDLC`. I will submit a pull request shortly.

**Comment by akhilles** [comment]
My understanding is that IEEE 802.3 only defines the polynomial and suggests (but doesn't require) an initial state. So, ISO-HDLC, BZIP2, MPEG-2 are all CRC algorithms that use the IEEE 802.3 polynomial. So, I'm hesitant to introduce this alias here.

Previous versions of `crc` did equate the IEEE 802.3 polynomial with just the ISO-HDLC algorithm, so I think that's a better place to add the alias (along with a comment that explains that CRC_32_IEEE could also refer to other algorithms besides CRC_32_ISO_HDLC).

**Comment by BartMassey** [comment]
Fair enough.

It took me about an hour to figure out which CRC I needed here, and that was partly because the older version of the `crc` crate didn't use the HDLC name for the PNG CRC, and nothing else really did either. I somehow missed that the link to the source catalog was to a document that lists things like this.

I don't know whether it would be worth adding CRC_32_IEEE_802_3_* type aliases here for those protocols with the 802.3 polynomial. Probably not.

Thanks again.

**Comment by akhilles** [comment]
@BartMassey wdyt about adding polynomial constants (https://github.com/akhilles/crc-catalog/pull/5)? This at least provides a path for getting from the name of a polynomial to it's algorithms.

**Comment by BartMassey** [comment]
This seems like a good general direction to me! I will add comments on that PR.
