### ISSUE TITLE
CRC-32-CKSUM does not match output from the actual `cksum` utility on linux

### ISSUE THREAD

**Issue by Lorilandly** [akhilles/crc-catalog#8]
Tested on Ubuntu22.04 && macOS 12.6

`cksum` output:
```
echo "/bin/bash" | cksum     
3521343861 10
```

Code:
```
use crc::{Crc, CRC_32_CKSUM};

fn main() {
    let crc = Crc::<u32>::new(&CRC_32_CKSUM);
    let test_str = b"/bin/bash\n"; \\ The newline is necessary to match `echo`
    println!("{:x?}: {}", &test_str, crc.checksum(test_str));
}
```
Output:
`[2f, 62, 69, 6e, 2f, 62, 61, 73, 68, a]: 2039341834`

**Comment by akhilles** [comment]
That's because the inputs are not the same in your example.

From https://pubs.opengroup.org/onlinepubs/7990989775/xcu/cksum.html:
> These n bits are the bits from the file ... followed by one or more octets representing the length of the file as a binary value, least significant octet first

```
$ echo -n "123456789" | cksum
930766865 9
```

```rust
fn main() {
    let test_str = b"123456789";
    let crc = crc::Crc::<u32>::new(&crc::CRC_32_CKSUM);
    let mut digest = crc.digest();
    digest.update(test_str);
    digest.update(&[test_str.len() as u8]);
    println!("{}", digest.finalize());
}
```

Output:
```
930766865
```

**Comment by Lorilandly** [comment]
Thanks a lot. Confirmed it works now.
