### ISSUE TITLE
Missing tags for versions 2.3.0 and 2.4.0

### ISSUE THREAD

**Issue by paolobarbolini** [akhilles/crc-catalog#9]
Hi! While scraping my dependencies from crates.io I've found this repository to be missing the tags for releases v2.3.0 and v2.4.0. Could those be added?

The exact commit ids can be found from:

* https://docs.rs/crate/crc-catalog/2.3.0/source/.cargo_vcs_info.json
* https://docs.rs/crate/crc-catalog/2.4.0/source/.cargo_vcs_info.json

**Comment by akhilles** [comment]
Ah, thanks for letting me know. Went ahead and pushed the tags. The commits were tagged on release, but only pushed to https://git.sr.ht/~akhil/crc-catalog, which is my primary version control.

**Comment by paolobarbolini** [comment]
Thanks for the quick fix. Closing now.
